研究:
  画像:
    - 画像処理
    - 曲線
    - ベクタ画像
    - アンチエイリアシング
  信号処理:
    - サンプリング
    - フーリエ変換
    - 解析信号
    - ヒルベルト変換
  計算:
    - 数式処理
    - Mathematica
    - プロット
    - 2進数
    - 記数法
    - 演算器
  異次元:
    - 4次元
    - フラクタル
    - 再帰曲線
    - ドラゴン曲線
  フィボナッチ:
    - 黄金比
    - フィボナッチ数
  哲学:
    - 哲学
    - 心理学
    - 認知科学
    - 顔
  AI:
    - 人工知能
    - 言語理解
  問題:
    - グラフ理論
    - 巡回セールスマン問題
    - コラッツ問題（3n+1問題）
  フォーマット:
    - JSON
    - XML
    - MathML
    - SVG

アート:
  アート分野:
    - デジタルアート
    - メディアアート
    - トリックアート
  アプリケーション:
    - Flash (ActionScript)
    - Illustrator
  音楽ジャンル:
    - テクノ(Electronic)
    - ドラムンベース
    - IDM
    - Chiptune
  ミュージシャン:
    - Autechre
    - Aphex Twin
    - Underworld
    - µ-Ziq
    - 電気グルーヴ
    - DE DE MOUSE
    - P-MODEL
  FF:
    - Final Fantasy
    - 植松伸夫
    - 崎元仁
    - 野村哲也
    - 吉田明彦
  文字:
    - フォント

その他趣味:
  0:
    - アイスクリーム
    - 甘味
  1:
    - お笑い
  2:
    - 漢字
  3:
    - ライフログ
    - SNS
