list:
  -
    title: '半熟語'
    path: '/hanjukugo/'
    dest: '/project/hanjukugo/'

  -
    title: 'GraphiCalPad'
    path: '/documents/graphicalpad/'
    dest: '/project/graphicalpad/'

  -
    title: 'WebClapPad'
    path: '/documents/webclappad/'
    dest: '/project/webclappad/'

  -
    title: 'waraken'
    path: '/waraken/'
    dest: '/project/waraken/'

  -
    title: 'なんでも魔法。'
    path: '/magic/'
    dest: '/project/nandemo-magic/'

  -
    title: 'ポポポポケモン！'
    path: '/pokemon/'
    dest: '/project/po3pokemon/'

  -
    title: 'いいノック'
    path: '/iiknock/'
    dest: '/project/iiknock/'

  -
    title: '物智数'
    path: '/planar_binary/'
    dest: '/documents/butchi-number/'

  -
    title: '2進数の平面的表現に関する考察'
    path: '/documents/'
    filename: 'b-thesis.html'
    dest: '/org/ku/b-thesis/presentation/'

  -
    title: 'エンタテインメントコンピューティング2008発表資料'
    path: '/documents/'
    filename: 'ec2008presentation.html'
    dest: '/publication/ec2008/'

  -
    title: '非周期的な画素配置を持つCMOSイメージセンサの基礎検討'
    path: '/documents/'
    filename: 'icd200707presentation.html'
    dest: '/publication/icd200707/'

  -
    title: 'WISS2008デモ'
    path: '/documents/'
    filename: 'wiss2008demo.html'
    dest: '/publication/wiss2008/demo/'

  -
    title: '第85回音楽情報科学研究会デモ'
    path: '/documents/mus85demo/'
    dest: '/publication/sigmus85/demo/'

  -
    title: '第105回 音楽情報科学研究会'
    path: '/documents/mus105/'
    dest: '/publication/sigmus105/'
