notoryu:
  ttl:
    "ノトリュー"
  tag:
    - works
    - character
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p><i>ノトリューは蛇の仙人（自称）です。空もちょっとだけ飛べます。じつは龍なのかもしれません。
    森の主なのでご年配ではありますが、子どもたちとも仲良く接してくれます。
    能登の「能」の字をモチーフに描きました。</i></p>
      <p><a href="http://www.pref.ishikawa.jp/kodomoseisaku/notoro-kettei.html">「ノトロ」</a>という「ト○ロ」に激似な名前のマスコットキャラクターとして応募した作品。<a href="http://ameblo.jp/poisontv/entry-10120739952.html">モリゾーとキッコロに激似なキャラクター</a>に負けてあえなく落選。</p>
    '

kenken:
  ttl:
    "研犬"
  tag:
    - works
    - character
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>金沢大学IT教育推進プログラム主催の学生e-Learning作品コンテストに応募した作品。</p>
    '

kagafuwanko:
  ttl:
    "かがふわんこ"
  tag:
    - works
    - character
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p><i>加賀麩をモチーフに制作しました。上から細工麩、生麩、車麩、すだれ麩、おつゆ麩です。</i></p>
      <p><a href="http://eatx.bp-musashi.jp/09award.html">eAT&quot;09アワード</a>に応募した作品。</p>
    '

newgo:
  ttl:
    "1(仮)"
  tag:
    - works
    - music
  ext:
    mp3
  extThumb:
    png

travelli:
  ttl:
    "トラベり(仮)"
  tag:
    - works
    - music
  ext:
    mp3
  extThumb:
    png

prime:
  ttl:
    "prime(仮)"
  tag:
    - works
    - music
  ext:
    mp3
  extThumb:
    png

dot-jp:
  ttl:
    "dot jp(仮)"
  tag:
    - works
    - music
  ext:
    mp3
  extThumb:
    png

selection:
  ttl:
    "selection(仮)"
  tag:
    - works
    - music
  ext:
    mp3
  extThumb:
    png

first-battle:
  ttl:
    "First Battle(仮)"
  tag:
    - works
    - music
  ext:
    mp3
  extThumb:
    png

outskirts-dungeon:
  ttl:
    "場末のダンジョン(仮)"
  tag:
    - works
    - music
  ext:
    mp3
  extThumb:
    png

suzumi:
  ttl:
    "suz(仮)"
  tag:
    - works
    - music
  ext:
    mp3
  extThumb:
    png

gray-code-counter-song:
  ttl:
    "グレイコードカウンタの歌"
  tag:
    - works
    - music
  youtube:
    "v64F7YaY27U"
  extThumb:
    png

bion:
  ttl:
    "bion（倍音）"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>両対数極座標。</p>
    '

waon:
  ttl:
    "waon（輪音）"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>『bion』を同心円上に並べた形。</p>
    '

geometry-3456:
  ttl:
    "3456"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>正4面体、正8面体、正20面体、平面を上から見た形。</p>
    '

star:
  ttl:
    "star"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>36°、72°、108°のいずれかを含む2等辺3角形で構成される形。</p>
    '

drop-into:
  ttl:
    "Drop into..."
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>水は空気の中を落ち、空気は水の中を落ちている。</p>
    '

beer-and-cocktail:
  ttl:
    "Beer & Cocktail"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>水は空気の中を落ち、空気は水の中を落ちている。</p>
    '

delta-pulse:
  ttl:
    "DeltaΔPulse"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>ギリシャ文字「Δ」と<a href="http://ja.wikipedia.org/wiki/%E3%83%87%E3%82%A3%E3%83%A9%E3%83%83%E3%82%AF%E3%81%AE%E3%83%87%E3%83%AB%E3%82%BF%E9%96%A2%E6%95%B0">ディラックのデルタ関数</a>（グラフ描画時の上矢印「↑」）がかかっている。</p>
    '

golden-tree:
  ttl:
    "黄金木"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>黄金比とフィボナッチ数。</p>
    '

self-folding:
  ttl:
    "自畳"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>QRコードには四字熟語が埋め込まれている。</p>
    '

enki-do:
  ttl:
    "EnkiDo"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>塩基配列アデニン（A）、チミン（T）、シトシン（C）、グアニン（G）。</p>
    '

quark:
  ttl:
    "quark"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>アップ、ダウン、チャーム、ストレンジ、トップ、ボトム。6種類のクォーク。</p>
    '

time-2005-march.gif:
  ttl:
    "2005年春用デスクトップ壁紙"
  tag:
    - works
    - design
  ext:
    gif
  extThumb:
    png
  desc:
    '
      <p>2005年春用デスクトップ壁紙。</p>
    '

web-stockings:
  ttl:
    "蜘蛛の巣トッキング"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>2010年度美術部新年展の作品。「大晦日に病院の待合室でクモがストッキングをゆっくりかぶった」というお題を頂いて制作。芥川龍之介の「蜘蛛の糸」をモチーフに、病院で生死をさまよう人間を表現。</p>
    '

shin-go-ki:
  ttl:
    "新合機"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>「合」という字には一つの屋根の下で人や物が一緒になるという意味が込められていると考えます。信号機を男女の出会いに見立てています。</p>
    '

copy-to-trashbox:
  ttl:
    "ごみ箱にコピー"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>意味無いシリーズ: ごみ箱にファイルをコピーしたら捨ててないのと同じ。</p>
    '

tercet-rest:
  ttl:
    "三連休符"
  tag:
    - works
    - design
    - iminai-series
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>意味無いシリーズ: 三連休符は全休符と同じ。</p>
    '

zero-plus-zero:
  ttl:
    "((((0+0))))"
  tag:
    - works
    - design
    - iminai-series
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>意味無いシリーズ: 数式をいくつの括弧で括っても結果は同じ。</p>
    '

lion-110-o:
  ttl:
    "110のO"
  tag:
    - works
    - design
    - iminai-series
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>百獣の王、ポンデライオン。Oの個数を数えてみよう。</p>
    '

itabasamies:
  ttl:
    "イタバサミーズ"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>後津サリ、板場サミ、前野メリの3人は<a href="http://twitter.com/zougoroku" target="_blank">Twitter「造語録」(@zougoroku)</a>から生まれたキャラクターです。</p>
    '

rotation:
  ttl:
    "回転"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>回ってます。</p>
    '

value-of-company:
  ttl:
    "企業の価値"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>高ければ高いほど高いのか。</p>
    '

jigsaw-qr:
  ttl:
    "ジグソーQR"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>QRコードのドットをジグソーパズルのピースにしてみました。ちゃんと携帯電話で読み取れます。試してみよう！<br>正方格子状のデータを記述するのは簡単ですが、正方格子の境目のデータを記述するのは一工夫要ります。</p>
    '

blinder:
  ttl:
    "目■■線"
  tag:
    - works
    - design
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>「目隠し線」の「隠し」を隠すことによって残るもの。</p>
      <p>人は顔を見るとき、80%のシカク情報を目から受け取っていると言われています。</p>
      <p>2012年「四角展」出展作品。</p>
    '

newcomer-exhibition-poster-2003.png:
  ttl:
    "2003年度美術部新人展ポスター"
  tag:
    - works
    - design
    - ads
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>2003年度美術部新人展ポスター。</p>
    '

newcomer-exhibition-sign-2003:
  ttl:
    "2003年度美術部新人展立看板"
  tag:
    - works
    - design
    - ads
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>2003年度美術部新人展立看板。</p>
    '

welcome-2004:
  ttl:
    "2004年度美術部新歓展ポスター"
  tag:
    - works
    - design
    - ads
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>2004年度美術部新歓展ポスター。</p>
    '

nanigashitai-flier-2008.jpg:
  ttl:
    "「ぼくたち一体なにがしたい！？」フライヤー"
  tag:
    - works
    - design
    - ads
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>所属グループ「某隊」のライブ「ぼくたち一体なにがしたい！？」フライヤー。</p>
    '

hanami-flier:
  ttl:
    "花見フライヤー"
  tag:
    - works
    - design
    - ads
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>研究室行事の花見（2007年）のフライヤー。</p>
    '

fine-char-actors:
  ttl:
    "Fine CharActors"
  tag:
    - works
    - design
    - ads
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>金沢大学美術部新年展2009ポスターより。</p>
      <p>「金沢大学美術部」のパーツを利用して「文字展」を作っている。</p>
    '

shikakuten-logo:
  ttl:
    "四角展ロゴ"
  tag:
    - works
    - design
    - ads
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>美術部新年展「四角展」（2012年）のポスター用ロゴ</p>
    '

logo-acaneco-sns:
  ttl:
    "AcaNeCoロゴ"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>AcaNeCo（金沢大学SNS）ロゴ（SNS版）。</p>
    '

logo-acaneco-portal:
  ttl:
    "AcaNeCoロゴ"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>AcaNeCo（金沢大学SNS）ロゴ（アカンサスポータル版）。</p>
    '

logo-alpha-1:
  ttl:
    "Alpha"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-alpha-2:
  ttl:
    "Alpha"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-alpha-3:
  ttl:
    "Alpha"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-roof:
  ttl:
    "Roof"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-blade:
  ttl:
    "Blade"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-scene:
  ttl:
    "Scene"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-joint:
  ttl:
    "Joint"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-jelly:
  ttl:
    "Jelly"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-heart:
  ttl:
    "Heart"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-ghost:
  ttl:
    "Ghost"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-fade:
  ttl:
    "Fade"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-dream:
  ttl:
    "Dream"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-pro:
  ttl:
    "Pro"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-treatment:
  ttl:
    "Treatment"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-club:
  ttl:
    "Club"
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

newyear-2004:
  ttl:
    "2004年年賀状"
  tag:
    - works
    - design
    - newyear
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>「申」が猿のキャラクターに。</p>
    '

newyear-2008:
  ttl:
    "2008年年賀画像"
  tag:
    - works
    - design
    - newyear
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>子曰、「注仲忠虫宙（ちゅうちゅうちゅうちゅうちゅう）。」</p>
    '

newyear-2011:
  ttl:
    "2011年年賀状"
  tag:
    - works
    - design
    - newyear
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p><a href="http://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A3%E3%83%9C%E3%83%8A%E3%83%83%E3%83%81%E6%95%B0#.E5.85.8E.E3.81.AE.E5.95.8F.E9.A1.8C" target="_blank">フィボナッチのウサギ</a>。</p>
    '

newyear-2012:
  ttl:
    "2012年年賀状"
  tag:
    - works
    - design
    - newyear
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p><a href="http://www.google.co.jp/search?q=%83h%83%89%83S%83%93%8B%C8%90%FC" target="_blank">ドラゴン曲線</a>を2つ重ねたTwindragon。</p>
    '

newyear-2013:
  ttl:
    "2013年年賀状"
  tag:
    - works
    - design
    - newyear
  ext:
    png
  extThumb:
    png
  desc:
    '
      <p>自己加算フラクタルによる「巳」。</p>
    '

butchi-sutra:
  ttl:
    "物智経"
  tag:
    - works
    - poem
  ext:
    png
  extThumb:
    png
  body:
    '
      <p>平成二十年師走十二日卯の刻(西暦2008年12月12日6時8分)</p>
      <p>有</p>

      <p>良？</p>

      <p>無。</p>

      <p>而是良。</p>

      <p>死？</p>
      <p>生。</p>
      <p>有時而死。</p>
      <p>時実而甚。</p>
      <p>側時有良。</p>
      <p>傍者勇者。</p>
      <p>笑。</p>
      <p>∥</p>
      <p>一</p>
      <p>〇</p>
      <p>。</p>
      <p>.</p>

      <h3>意訳</h3>
      <p>この世は「有」の世界である。</p>
      <p>それは良いのか？</p>
      <p>その答えは無い。</p>
      <p>しかし、良いと定義する。</p>
      <p>死ぬの？</p>
      <p>生きる。</p>
      <p>時間があるから死ぬのである。</p>
      <p>しかし、時間というのは細分すれば無限に有る。</p>
      <p>そして、時間が有るからこそ良いのである。</p>
      <p>あなたの傍らには勇者がいる。</p>
      <p>笑えばいいと思うよ。</p>
      <p>=10。.（2進数における10、つまり2と同等になる。）</p>
    '

poem-kokoro:
  ttl:
    "心"
  tag:
    - works
    - poem
  ext:
    png
  extThumb:
    png
  body:
    '
      <p>私はあなたの心です。私はあなたの気持ちをもちろんすべて知っています。あなたは私の気持ちをどれだけ知っていますか？</p>
    '

poem-nothing:
  ttl:
    "無"
  tag:
    - works
    - poem
  ext:
    png
  extThumb:
    png
  body:
    '
      <p>私は無という存在です。私があなたに伝えることは何も無く、むろん存在でもない。私はそのようなことを語りかけることは無く、無い。</p>
    '

poem-anohibi:
  ttl:
    "今が「あの日々」となるように"
  tag:
    - works
    - poem
  ext:
    png
  extThumb:
    png
  body:
    '
      <p>何かにつけてはタスクをこなす日々</p>
      <p>食っちゃ寝 学んじゃ寝 働いちゃ寝 恋しちゃ寝</p>
      <p>もっとハート揺れ動かさなくちゃね</p>
      <p>遠い未来、自分が輝くためにやらなきゃいけないこと</p>
      <p>それはいま輝くこと</p>
    '

poem-yuki-rinrin:
  ttl:
    "勇气凛凛"
  tag:
    - works
    - poem
  ext:
    png
  extThumb:
    png
  body:
    '
      <p>勇气凛凛　　簗瀬巍</p>
      <br>
      <p>勇气之鈴鳴凛凛　奇怪之冒険流流</p>
      <p>餡食伽哩之面包　果醤牛乾酪弾弾</p>
      <p>黴菌男目玉爛爛　餡面包男何不行</p>
      <p>驚悸女使人悸悸　果子醤翁顔優雅</p>
      <p>牛酪子奔走騒騒　誰忌餡面包男乎</p>
      <br>

      <h3>書き下し</h3>
      <p>勇気の鈴 凛凛(りんりん)</p>
      <p>奇怪なる冒険 流流(るんるん)</p>
      <p>餡・食・伽哩(かりー)の麺麭</p>
      <p>果醤(じゃむ)、牛・乾酪 弾弾</p>
      <p>黴菌(ばいきん)男の目玉 爛爛(らんらん)</p>
      <p>餡麺麭男(あんぱんまん) 何ぞ行かざる</p>
      <p>驚悸女 人をして悸悸(どきどき)せしむ</p>
      <p>果子醤翁の顔 優雅なり</p>
      <p>牛酪子 奔走すること騒騒(ばたばた)</p>
      <p>誰ぞ餡麺麭男を忌むか</p>
      <br>

      <h3>現代語訳</h3>
      <p>勇気の鈴がリンリンと鳴り、</p>
      <p>不思議な冒険はルンルンと続く。</p>
      <p>アンパン、食パン､カレーパン、</p>
      <p>ジャム、バター、チーズと食材は続々と出る。</p>
      <p>バイキンマンの目玉はらんらんと光る。</p>
      <p>アンパンマンが行かない事があろうか､いやない。</p>
      <p>ドキンちゃんは人をドキドキさせ、</p>
      <p>バタコさんはバタバタと走る。</p>
      <p>アンパンマンを嫌うものがいるだろうか､いやいない。</p>

      <h3>出典</h3>
      <ul>
       <li>
        <a href="http://www.utamap.com/showkasi.php?surl=E02028" target="_blank">勇気りんりん</a>
       </li>
      </ul>
    '

poem-anpanman-march:
  ttl:
    "餡麺麭男行進曲"
  tag:
    - works
    - poem
  ext:
    png
  extThumb:
    png
  body:
    '
      <p>餡麺麭男行進曲　　簗瀬巍</p>
      <br>
      <p>為皆不畏、吾友愛勇気耳。</p>
      <p>何子幸、何子為悦。不解而終、吾嫌其。不忘夢、不零涙、而子飛無限。</p>
      <p>為皆不畏、吾友愛勇気耳。</p>
      <p>嗚呼何優餡麺麭男、為守皆夢行。</p>
      <br>

      <h3>出典</h3>
      <ul>
       <li>
        <a href="http://www.utamap.com/showkasi.php?surl=E02014" target="_blank">アンパンマンのマーチ</a>
       </li>
      </ul>
    '
