notoryu:
  title:
    'ノトリュー'
  tag:
    - works
    - character
  thumb:
    'notoryu.png'

kenken:
  title:
    '研犬'
  tag:
    - works
    - character
  thumb:
    'kenken.png'

kagafuwanko:
  title:
    'かがふわんこ'
  tag:
    - works
    - character
  thumb:
    'kagafuwanko.png'

newgo:
  title:
    '1(仮)'
  tag:
    - works
    - music
  thumb:
    'music.png'

travelli:
  title:
    'トラベり(仮)'
  tag:
    - works
    - music
  thumb:
    'music.png'

prime:
  title:
    'prime(仮)'
  tag:
    - works
    - music
  thumb:
    'music.png'

dot-jp:
  title:
    'dot jp(仮)'
  tag:
    - works
    - music
  thumb:
    'music.png'

selection:
  title:
    'selection(仮)'
  tag:
    - works
    - music
  thumb:
    'music.png'

first-battle:
  title:
    'First Battle(仮)'
  tag:
    - works
    - music
  thumb:
    'music.png'

outskirts-dungeon:
  title:
    '場末のダンジョン(仮)'
  tag:
    - works
    - music
  thumb:
    'music.png'

suzumi:
  title:
    'suz(仮)'
  tag:
    - works
    - music
  thumb:
    'music.png'

gray-code-counter-song:
  title:
    'グレイコードカウンタの歌'
  tag:
    - works
    - music
  thumb:
    'music.png'

bion:
  title:
    'bion（倍音）'
  tag:
    - works
    - design
  thumb:
    'bion.png'

waon:
  title:
    'waon（輪音）'
  tag:
    - works
    - design
  thumb:
    'waon.png'

geometry-3456:
  title:
    '3456'
  tag:
    - works
    - design
  thumb:
    'geometry-3456.png'

star:
  title:
    'star'
  tag:
    - works
    - design
  thumb:
    'star.png'

drop-into:
  title:
    'Drop into...'
  tag:
    - works
    - design
  thumb:
    'drop-into.png'

beer-and-cocktail:
  title:
    'Beer & Cocktail'
  tag:
    - works
    - design
  thumb:
    'beer-and-cocktail.png'

delta-pulse:
  title:
    'DeltaΔPulse'
  tag:
    - works
    - design
  thumb:
    'delta-pulse.png'

golden-tree:
  title:
    '黄金木'
  tag:
    - works
    - design
  thumb:
    'golden-tree.png'

self-folding:
  title:
    '自畳'
  tag:
    - works
    - design
  thumb:
    'self-folding.png'

enki-do:
  title:
    'EnkiDo'
  tag:
    - works
    - design
  thumb:
    'enki-do.png'

quark:
  title:
    'quark'
  tag:
    - works
    - design
  thumb:
    'quark.png'

datetime-2005-march:
  title:
    '2005年春用デスクトップ壁紙'
  tag:
    - works
    - design
  thumb:
    'datetime-2005-march.png'

web-stockings:
  title:
    '蜘蛛の巣トッキング'
  tag:
    - works
    - design
  thumb:
    'web-stockings.png'

shin-go-ki:
  title:
    '新合機'
  tag:
    - works
    - design
  thumb:
    'shin-go-ki.png'

copy-to-trashbox:
  title:
    'ごみ箱にコピー'
  tag:
    - works
    - design
    - iminai-series
  thumb:
    'copy-to-trashbox.png'

tercet-rest:
  title:
    '三連休符'
  tag:
    - works
    - design
    - iminai-series
  thumb:
    'tercet-rest.png'

zero-plus-zero:
  title:
    '((((0+0))))'
  tag:
    - works
    - design
    - iminai-series
  thumb:
    'zero-plus-zero.png'

lion-110-o:
  title:
    '110のO'
  tag:
    - works
    - design
    - iminai-series
  thumb:
    'lion-110-o.png'

itabasamies:
  title:
    'イタバサミーズ'
  tag:
    - works
    - design
  thumb:
    'itabasamies.png'

rotation:
  title:
    '回転'
  tag:
    - works
    - design
  thumb:
    'rotation.png'

value-of-company:
  title:
    '企業の価値'
  tag:
    - works
    - design
  thumb:
    'value-of-company.png'

jigsaw-qr:
  title:
    'ジグソーQR'
  tag:
    - works
    - design
  thumb:
    'jigsaw-qr.png'

blinder:
  title:
    '目■■線'
  tag:
    - works
    - design
  thumb:
    'blinder.png'

newcomer-exhibition-poster-2003:
  title:
    '2003年度美術部新人展ポスター'
  tag:
    - works
    - design
    - ads
  thumb:
    'newcomer-exhibition-poster-2003.png'

newcomer-exhibition-sign-2003:
  title:
    '2003年度美術部新人展立看板'
  tag:
    - works
    - design
    - ads
  thumb:
    'newcomer-exhibition-sign-2003.png'

welcome-2004:
  title:
    '2004年度美術部新歓展ポスター'
  tag:
    - works
    - design
    - ads
  thumb:
    'welcome-2004.png'

nanigashitai-flier-2008:
  title:
    '「ぼくたち一体なにがしたい！？」フライヤー'
  tag:
    - works
    - design
    - ads
  thumb:
    'nanigashitai-flier-2008.png'

hanami-flier:
  title:
    '花見フライヤー'
  tag:
    - works
    - design
    - ads
  thumb:
    'hanami-flier.png'

fine-char-actors:
  title:
    'Fine CharActors'
  tag:
    - works
    - design
    - ads
  thumb:
    'fine-char-actors.png'

shikakuten-logo:
  title:
    '四角展ロゴ'
  tag:
    - works
    - design
    - ads
  thumb:
    'shikakuten-logo.png'

logo-acaneco-sns:
  title:
    'AcaNeCoロゴ'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-acaneco-sns.png'

logo-acaneco-portal:
  title:
    'AcaNeCoロゴ'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-acaneco-portal.png'

logo-alpha-1:
  title:
    'Alpha'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-alpha-1.png'

logo-alpha-2:
  title:
    'Alpha'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-alpha-2.png'

logo-alpha-3:
  title:
    'Alpha'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-alpha-3.png'

logo-roof:
  title:
    'Roof'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-roof.png'

logo-blade:
  title:
    'Blade'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-blade.png'

logo-scene:
  title:
    'Scene'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-scene.png'

logo-joint:
  title:
    'Joint'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-joint.png'

logo-jelly:
  title:
    'Jelly'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-jelly.png'

logo-heart:
  title:
    'Heart'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-heart.png'

logo-ghost:
  title:
    'Ghost'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-ghost.png'

logo-fade:
  title:
    'Fade'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-fade.png'

logo-dream:
  title:
    'Dream'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-dream.png'

logo-pro:
  title:
    'Pro'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-pro.png'

logo-treatment:
  title:
    'Treatment'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-treatment.png'

logo-club:
  title:
    'Club'
  tag:
    - works
    - design
    - logo
  thumb:
    'logo-club.png'

newyear-2004:
  title:
    '2004年年賀状'
  tag:
    - works
    - design
    - newyear
  thumb:
    'newyear-2004.png'

newyear-2008:
  title:
    '2008年年賀画像'
  tag:
    - works
    - design
    - newyear
  thumb:
    'newyear-2008.png'

newyear-2011:
  title:
    '2011年年賀状'
  tag:
    - works
    - design
    - newyear
  thumb:
    'newyear-2011.png'

newyear-2012:
  title:
    '2012年年賀状'
  tag:
    - works
    - design
    - newyear
  thumb:
    'newyear-2012.png'

newyear-2013:
  title:
    '2013年年賀状'
  tag:
    - works
    - design
    - newyear
  thumb:
    'newyear-2013.png'

butchi-sutra:
  title:
    '物智経'
  tag:
    - works
    - poem
  thumb:
    'writing.png'

poem-kokoro:
  title:
    '心'
  tag:
    - works
    - poem
  thumb:
    'writing.png'

poem-nothing:
  title:
    '無'
  tag:
    - works
    - poem
  thumb:
    'writing.png'

poem-anohibi:
  title:
    '今が「あの日々」となるように'
  tag:
    - works
    - poem
  thumb:
    'writing.png'

poem-yuki-rinrin:
  title:
    '勇气凛凛'
  tag:
    - works
    - poem
  thumb:
    'writing.png'

poem-anpanman-march:
  title:
    '餡麺麭男行進曲'
  tag:
    - works
    - poem
  thumb:
    'writing.png'
