notoryu:
  title:
    'ノトリュー'
  tag:
    - works
    - character

kenken:
  title:
    '研犬'
  tag:
    - works
    - character

kagafuwanko:
  title:
    'かがふわんこ'
  tag:
    - works
    - character

newgo:
  title:
    '1(仮)'
  tag:
    - works
    - music

travelli:
  title:
    'トラベり(仮)'
  tag:
    - works
    - music

prime:
  title:
    'prime(仮)'
  tag:
    - works
    - music

dot-jp:
  title:
    'dot jp(仮)'
  tag:
    - works
    - music

selection:
  title:
    'selection(仮)'
  tag:
    - works
    - music

first-battle:
  title:
    'First Battle(仮)'
  tag:
    - works
    - music

outskirts-dungeon:
  title:
    '場末のダンジョン(仮)'
  tag:
    - works
    - music

suzumi:
  title:
    'suz(仮)'
  tag:
    - works
    - music

gray-code-counter-song:
  title:
    'グレイコードカウンタの歌'
  tag:
    - works
    - music

bion:
  title:
    'bion（倍音）'
  tag:
    - works
    - design

waon:
  title:
    'waon（輪音）'
  tag:
    - works
    - design

geometry-3456:
  title:
    '3456'
  tag:
    - works
    - design

star:
  title:
    'star'
  tag:
    - works
    - design

drop-into:
  title:
    'Drop into...'
  tag:
    - works
    - design

beer-and-cocktail:
  title:
    'Beer & Cocktail'
  tag:
    - works
    - design

delta-pulse:
  title:
    'DeltaΔPulse'
  tag:
    - works
    - design

golden-tree:
  title:
    '黄金木'
  tag:
    - works
    - design

self-folding:
  title:
    '自畳'
  tag:
    - works
    - design

enki-do:
  title:
    'EnkiDo'
  tag:
    - works
    - design

quark:
  title:
    'quark'
  tag:
    - works
    - design

datetime-2005-march:
  title:
    '2005年春用デスクトップ壁紙'
  tag:
    - works
    - design

web-stockings:
  title:
    '蜘蛛の巣トッキング'
  tag:
    - works
    - design

shin-go-ki:
  title:
    '新合機'
  tag:
    - works
    - design

copy-to-trashbox:
  title:
    'ごみ箱にコピー'
  tag:
    - works
    - design
    - iminai-series

tercet-rest:
  title:
    '三連休符'
  tag:
    - works
    - design
    - iminai-series

zero-plus-zero:
  title:
    '((((0+0))))'
  tag:
    - works
    - design
    - iminai-series

lion-110-o:
  title:
    '110のO'
  tag:
    - works
    - design
    - iminai-series

itabasamies:
  title:
    'イタバサミーズ'
  tag:
    - works
    - design

rotation:
  title:
    '回転'
  tag:
    - works
    - design

value-of-company:
  title:
    '企業の価値'
  tag:
    - works
    - design

jigsaw-qr:
  title:
    'ジグソーQR'
  tag:
    - works
    - design

blinder:
  title:
    '目■■線'
  tag:
    - works
    - design

newcomer-exhibition-poster-2003:
  title:
    '2003年度美術部新人展ポスター'
  tag:
    - works
    - design
    - ads

newcomer-exhibition-sign-2003:
  title:
    '2003年度美術部新人展立看板'
  tag:
    - works
    - design
    - ads

welcome-2004:
  title:
    '2004年度美術部新歓展ポスター'
  tag:
    - works
    - design
    - ads

nanigashitai-flier-2008:
  title:
    '「ぼくたち一体なにがしたい！？」フライヤー'
  tag:
    - works
    - design
    - ads

hanami-flier:
  title:
    '花見フライヤー'
  tag:
    - works
    - design
    - ads

fine-char-actors:
  title:
    'Fine CharActors'
  tag:
    - works
    - design
    - ads

shikakuten-logo:
  title:
    '四角展ロゴ'
  tag:
    - works
    - design
    - ads

logo-acaneco-sns:
  title:
    'AcaNeCoロゴ'
  tag:
    - works
    - design
    - logo

logo-acaneco-portal:
  title:
    'AcaNeCoロゴ'
  tag:
    - works
    - design
    - logo

logo-alpha-1:
  title:
    'Alpha'
  tag:
    - works
    - design
    - logo
  ext:
    png
  extThumb:
    png

logo-alpha-2:
  title:
    'Alpha'
  tag:
    - works
    - design
    - logo

logo-alpha-3:
  title:
    'Alpha'
  tag:
    - works
    - design
    - logo

logo-roof:
  title:
    'Roof'
  tag:
    - works
    - design
    - logo

logo-blade:
  title:
    'Blade'
  tag:
    - works
    - design
    - logo

logo-scene:
  title:
    'Scene'
  tag:
    - works
    - design
    - logo

logo-joint:
  title:
    'Joint'
  tag:
    - works
    - design
    - logo

logo-jelly:
  title:
    'Jelly'
  tag:
    - works
    - design
    - logo

logo-heart:
  title:
    'Heart'
  tag:
    - works
    - design
    - logo

logo-ghost:
  title:
    'Ghost'
  tag:
    - works
    - design
    - logo

logo-fade:
  title:
    'Fade'
  tag:
    - works
    - design
    - logo

logo-dream:
  title:
    'Dream'
  tag:
    - works
    - design
    - logo

logo-pro:
  title:
    'Pro'
  tag:
    - works
    - design
    - logo

logo-treatment:
  title:
    'Treatment'
  tag:
    - works
    - design
    - logo

logo-club:
  title:
    'Club'
  tag:
    - works
    - design
    - logo

newyear-2004:
  title:
    '2004年年賀状'
  tag:
    - works
    - design
    - newyear

newyear-2008:
  title:
    '2008年年賀画像'
  tag:
    - works
    - design
    - newyear

newyear-2011:
  title:
    '2011年年賀状'
  tag:
    - works
    - design
    - newyear

newyear-2012:
  title:
    '2012年年賀状'
  tag:
    - works
    - design
    - newyear

newyear-2013:
  title:
    '2013年年賀状'
  tag:
    - works
    - design
    - newyear

butchi-sutra:
  title:
    '物智経'
  tag:
    - works
    - poem

poem-kokoro:
  title:
    '心'
  tag:
    - works
    - poem

poem-nothing:
  title:
    '無'
  tag:
    - works
    - poem

poem-anohibi:
  title:
    '今が「あの日々」となるように'
  tag:
    - works
    - poem

poem-yuki-rinrin:
  title:
    '勇气凛凛'
  tag:
    - works
    - poem

poem-anpanman-march:
  title:
    '餡麺麭男行進曲'
  tag:
    - works
    - poem
