# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 038d7c0d06b9da67142fbbc24c21c476adfbef2de5938fe87b52031f15275f515c451cdbb416a7d075304204e10e70ededc7b2c79f5ca5647c43f10cf188916f

test:
  secret_key_base: be49fcf66b519e52e1bdfe20663a14924fa1e923bf07cb8feb2e25b3f5f55206be75459c61d4ca65606d03f26b084188fc17bc637895adba7abb88a555ad0bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
